fc out_1.txt test_outputs/test1o.txt
fc out_2.txt test_outputs/test2o.txt
fc out_3.txt test_outputs/test3o.txt
fc out_4.txt test_outputs/test4o.txt
fc out_5.txt test_outputs/test5o.txt
fc out_6.txt test_outputs/test6o.txt
fc out_7.txt test_outputs/test7o.txt
fc out_8.txt test_outputs/test8o.txt
fc out_9.txt test_outputs/test9o.txt
fc out_10.txt test_outputs/test10o.txt
fc out_11.txt test_outputs/test11o.txt
fc out_12.txt test_outputs/test12o.txt
fc out_13.txt test_outputs/test13o.txt
fc out_14.txt test_outputs/test14o.txt
fc out_15.txt test_outputs/test15o.txt
fc out_16.txt test_outputs/test16o.txt
fc out_17.txt test_outputs/test17o.txt
fc out_18.txt test_outputs/test18o.txt
fc out_19.txt test_outputs/test19o.txt
fc out_20.txt test_outputs/test20o.txt
fc out_21.txt test_outputs/test21o.txt
fc out_22.txt test_outputs/test22o.txt
fc out_23.txt test_outputs/test23o.txt
fc out_24.txt test_outputs/test24o.txt
fc out_25.txt test_outputs/test25o.txt
fc out_26.txt test_outputs/test26o.txt
fc out_27.txt test_outputs/test27o.txt
fc out_28.txt test_outputs/test28o.txt
fc out_29.txt test_outputs/test29o.txt
